myhandJAVA/be09-2nd-myHandJava-momentours

momentours/src/main/java/com/myhandjava/momentours/config/AppConfig.java, momentours/src/main/java/com/myhandjava/momentours/diary/command/application/controller/DiaryController.java, momentours/src/main/java/com/myhandjava/momentours/diary/command/application/dto/DiaryDTO.java, momentours/src/main/java/com/myhandjava/momentours/diary/command/application/service/DiaryService.java, momentours/src/main/java/com/myhandjava/momentours/diary/command/application/service/DiaryServiceImpl.java, momentours/src/main/java/com/myhandjava/momentours/diary/command/domain/aggregate/Diary.java, momentours/src/main/java/com/myhandjava/momentours/diary/command/domain/repository/DiaryRepository.java, momentours/src/main/java/com/myhandjava/momentours/diary/command/domain/vo/RequestRegistDiaryVO.java, momentours/src/test/java/com/myhandjava/momentours/diary/command/application/service/DiaryServiceImplTests.java
---
name: 일기 등록 기능
about: 회원이 일기 작성하여 등록하는 기능
title: '일기 등록 #13 '
labels: BackEnd, feat
---
- ModelMapper를 추가하고 테이블명과 컬럼명을 바꾸면서 diaryNo가 auto_increment로 안되는 장애발견!
- DiaryDTO에 diaryNo이 있어서 그랬었다...
- ModelMapp클래스 추가와 gradle추가 yaml 파일에 ddl update로 변경!
=> feat: 일기 등록 기능 추가

momentours/src/main/java/com/myhandjava/momentours/diary/query/controller/DiaryController.java, momentours/src/main/java/com/myhandjava/momentours/diary/query/dto/DiaryDTO.java, momentours/src/main/java/com/myhandjava/momentours/diary/query/service/DiaryServiceImpl.java, momentours/src/main/java/com/myhandjava/momentours/file/query/dto/FileDTO.java, momentours/src/main/java/com/myhandjava/momentours/file/query/repository/FileMapper.java, momentours/src/main/resources/mappers/diary/DiaryMapper.xml, momentours/src/main/resources/mappers/file/FileMapper.xml, momentours/src/test/java/com/myhandjava/momentours/diary/query/service/DiaryServiceImplTests.java
---
name: 일기 조회 기능 구조 개선
about:
- diaryMapper.xml 컬럼명 바꾸기
- 일기 조회 시 파일 같이 조회하도록 추가
title: '일기 조회 기능 구조 개선 #37 '
labels: Backend, refactor
---
- 
- 
- 날자 포맷이 꽤 더럽습니다.
=> refactor: 일기 조회 기능 구조 개선

momentours/src/main/java/com/myhandjava/momentours/diary/command/application/controller/DiaryController.java, momentours/src/main/java/com/myhandjava/momentours/diary/command/application/service/DiaryService.java, momentours/src/main/java/com/myhandjava/momentours/diary/command/application/service/DiaryServiceImpl.java, momentours/src/main/java/com/myhandjava/momentours/diary/command/domain/vo/RequestRegistDiaryVO.java, momentours/src/main/java/com/myhandjava/momentours/file/command/application/service/FileService.java, momentours/src/main/java/com/myhandjava/momentours/file/command/application/service/FileServiceImpl.java, momentours/src/test/java/com/myhandjava/momentours/diary/command/application/service/DiaryServiceImplTests.java
---
name: 일기 등록 시 파일 저장
about: 일기 등록 시 내용에 첨부된 파일도 같이 저장 되도록 추가
title: ' #39 '
labels: Backend, refactor
---
- 아직도...java.nio.file.NoSuchFileException: C:\Users\Playdata\AppData\Local\Temp\tomcat.8080.730682372351394947\work\Tomcat\localhost\ROOT\upload_4f36fda4_ac7f_4b16_a28a_82739088a690_00000003.tmp 이 에러가 나네요... 로컬에 이미지 저장하는거 같긴한데,,,,흠
- 
3a">
=> refactor: 일기 등록 기능 구조 개선

momentours/src/main/java/com/myhandjava/momentours/config/MybatisConfiguration.java, momentours/src/main/java/com/myhandjava/momentours/momentcourse/query/repository/MomentCourseMapper.java, momentours/src/main/java/com/myhandjava/momentours/momentcourse/query/service/MomentCourseService.java, momentours/src/main/java/com/myhandjava/momentours/todocourse/query/controller/TodoCourseController.java, momentours/src/main/java/com/myhandjava/momentours/todocourse/query/dto/TodoCourseDTO.java, momentours/src/main/java/com/myhandjava/momentours/todocourse/query/repository/TodoCourseMapper.java, momentours/src/main/java/com/myhandjava/momentours/todocourse/query/service/TodoCourseService.java, momentours/src/main/java/com/myhandjava/momentours/todocourse/query/service/TodoCourseServiceImpl.java, momentours/src/main/resources/mappers/todocourse/TodoCourseMapper.xml, momentours/src/test/java/com/myhandjava/momentours/momentcourse/query/service/MomentCourseServiceImplTests.java, momentours/src/test/java/com/myhandjava/momentours/todocourse/query/service/TodoCourseServiceImplTests.java
---
name: 예정 코스 조회
about: 해당 커플의 예정 코스 전체 및 상세 조회 기능 개발
title: #43 
assignees: ''
---
- 
- 
- 
- [x] 테스트 코드를 이용한 예정 코스 전체 및 상세 조회 테스트
=> feat. 예정 코스 조회

momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/controller/ScheduleController.java, momentours/src/main/java/com/myhandjava/momentours/schedule/query/controller/ScheduleController.java, momentours/src/main/java/com/myhandjava/momentours/schedule/query/service/ScheduleServiceImpl.java, momentours/src/main/resources/mappers/schedule/ScheduleMapper.xml
---
name:  일정 관련 기능 응답을 ResponseMessage를 이용하도록 구조 수정
about: 요청 처리 후 필요한 정보들을 RseponseMessage 객체를 활용하여 반환하도록 수정함
title: #35
assignees: ''
---
- 
- 
-
=> refactor: 일정 기능 구조 개선

momentours/src/main/java/com/myhandjava/momentours/diary/query/dto/CommentDTO.java, momentours/src/main/java/com/myhandjava/momentours/diary/query/dto/DiaryDTO.java, momentours/src/main/java/com/myhandjava/momentours/diary/query/service/DiaryServiceImpl.java, momentours/src/main/resources/mappers/diary/DiaryMapper.xml, momentours/src/test/java/com/myhandjava/momentours/diary/query/service/DiaryServiceImplTests.java
---
name: 일기 댓글 조회 기능 개발
about: 일기 조회 시 댓글과 파일 다 조회하도록 개발
title: ' #51 '
labels: Backend, feat
---
- 
- 
- 일기 도메인 안에 댓글 기능 작성함!
=> feat: 일기 댓글 조회

momentours/src/main/java/com/myhandjava/momentours/diary/command/application/controller/CommentController.java, momentours/src/main/java/com/myhandjava/momentours/diary/command/application/service/CommentService.java, momentours/src/main/java/com/myhandjava/momentours/diary/command/application/service/CommentServiceImpl.java, momentours/src/main/java/com/myhandjava/momentours/diary/command/application/service/DiaryServiceImpl.java, momentours/src/main/java/com/myhandjava/momentours/diary/command/domain/repository/CommentRepository.java, momentours/src/test/java/com/myhandjava/momentours/diary/command/application/service/CommentServiceImplTests.java
---
name: 일기 댓글 삭제
about: 회원이 쓴 일기 댓글 삭제 기능 개발
title: ' #59 '
labels: Backend, feat
---
- 
- 
-
=> feat: 일기 댓글 삭제 기능 개발

momentours/src/main/java/com/myhandjava/momentours/diary/query/controller/DiaryController.java, momentours/src/main/java/com/myhandjava/momentours/diary/query/repository/DiaryMapper.java, momentours/src/main/java/com/myhandjava/momentours/diary/query/service/DiaryService.java, momentours/src/main/java/com/myhandjava/momentours/diary/query/service/DiaryServiceImpl.java, momentours/src/main/resources/mappers/diary/DiaryMapper.xml, momentours/src/test/java/com/myhandjava/momentours/diary/query/service/DiaryServiceImplTests.java
---
name: 일기 전체 리스트 조회 기능 개발
about: 일기 페이지에서 커플들이 쓴 모든 일기 리스트를 조회하는 기능!
title: ' #63 '
labels: Beckend, feat
---
- 
- 
-
=> feat: 일기 전체 조회 기능 추가

momentours/build.gradle, momentours/src/main/java/com/myhandjava/momentours/config/AppConfig.java, momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/controller/RandomQuestionAndReplyController.java, momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/OpenAIService.java, momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/RandomQuestionAndReplyService.java, momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/RandomQuestionAndReplyServiceImpl.java
---
name: 커플 고유 랜덤질문 생성
about: openai api를 활용한 커플별 고유 랜덤질문 생성 기능을 개발했습니다.
title: ''
assignees: ''
---
- api key가 포함된 yml파일을 올렸다가 오류가 났었습니다..
- 
- gradle과 appconfig를 대폭 수정했습니다.
=> feat: 커플별 고유 랜덤질문 생성 기능 개발

momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/controller/MomentCourseController.java, momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/service/MomentCourseService.java, momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/service/MomentCourseServiceImpl.java, momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/domain/repository/MomentCourseRepository.java, momentours/src/test/java/com/myhandjava/momentours/momentcourse/command/application/service/MomentCourseServiceImplTests.java
---
name: 추억코스 삭제
about: 커플이 작성한 추억코스 삭제 기능 개발
title: ' #84 '
labels: backend, feat
---
- 
- 
-
=> feat: 추억코스 삭제

momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/controller/MomentCourseController.java, momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/service/MomentCourseService.java, momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/service/MomentCourseServiceImpl.java, momentours/src/test/java/com/myhandjava/momentours/momentcourse/command/application/service/MomentCourseServiceImplTests.java
---
name: 추억코스 좋아요/취소 기능
about: 추억 코스 좋아요와 좋아요 취소 기능 개발
title: ' #90 '
labels: backend, feat
---
- 
- 
- db가 연동이 안되어있어서 테스트를 못해봤습니당! 내일 테스트 해볼 예정!
=> feat: 추억코스 좋아요/취소 기능

momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/controller/MomentCourseController.java, momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/dto/FavoriteDTO.java, momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/service/MomentCourseService.java, momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/service/MomentCourseServiceImpl.java, momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/domain/aggregate/Favorite.java, momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/domain/repository/FavoriteRepository.java
---
name: 추억코스 즐겨찾기/취소 기능
about: 추억코스 즐겨찾기 기능과 취소 기능 개발
즐겨찾기 되어 있으면 누를때 취소하고 되어 있지 않으면 즐겨찾기 추가하는 기능
title: ' #92 '
labels: backend, feat
---
- 
- 
- 기능은 만들어 뒀는데 내일 테스트 해봐야함!!
=> feat: 추억코스 즐겨찾기/취소 기능

momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/service/MomentCourseServiceImpl.java
---
name: 추억 코스 수정 코드 수정
about: 추억 코스 수정 기능 테스트 코드 오류 
title: ' #95 '
labels: backend, refactor
---
- 그냥 serviceImpl에 값을 매개변수를 잘못 넣었습니다...
- 
-
=> refactor: 추억 코스 수정 기능 코드 수정

momentours/src/main/java/com/myhandjava/momentours/couple/command/application/controller/CoupleController.java, momentours/src/main/java/com/myhandjava/momentours/couple/command/application/dto/CoupleDTO.java, momentours/src/main/java/com/myhandjava/momentours/couple/command/application/service/CoupleService.java, momentours/src/main/java/com/myhandjava/momentours/couple/command/application/service/CoupleServiceImpl.java, momentours/src/main/java/com/myhandjava/momentours/couple/command/domain/repository/CoupleRepository.java, momentours/src/main/java/com/myhandjava/momentours/couple/command/domain/vo/CoupleRegistNumberVO.java, momentours/src/main/java/com/myhandjava/momentours/couple/command/domain/vo/CoupleRegistVO.java, momentours/src/main/java/com/myhandjava/momentours/couple/command/domain/vo/CoupleUpdateVO.java, momentours/src/main/java/com/myhandjava/momentours/couple/query/service/CoupleServiceImpl.java, momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/RandomQuestionAndReplyService.java, momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/RandomQuestionAndReplyServiceImpl.java
---
name: 커플 생성 기능 구현
about: 회원 번호 2개를 받아 커플 정보를 입력하는 창으로 리다이렉트 보낸 후 정보를 입력하면 회원 번호가 커플 클래스에 자동으로 set
title: ''
assignees: ''
---
- 
- 
-
=> feat: 회원 번호 2개 받아서 커플 정보 입력하는 창으로 안내 후 정보를 입력하면 회원 번호 자동 set까지 구현

momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/dto/FavoriteDTO.java, momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/service/MomentCourseServiceImpl.java, momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/domain/aggregate/Favorite.java, momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/domain/repository/FavoriteRepository.java, momentours/src/test/java/com/myhandjava/momentours/momentcourse/command/application/service/MomentCourseServiceImplTests.java
---
name: 추억 코스 즐겨찾기 코드 수정
about: 추억 코스 즐겨찾기 부분 테스트 코드 작성과 약간의 코드 수정
title: ' #92 '
assignees: ''
---
- 메소드명 잘못함...
- 
-
=> refator: 추억 코스 즐겨찾기 코드 수정

momentours/src/main/java/com/myhandjava/momentours/couple/command/application/controller/CoupleController.java, momentours/src/main/java/com/myhandjava/momentours/couple/command/application/service/CoupleServiceImpl.java, momentours/src/main/java/com/myhandjava/momentours/couple/command/domain/vo/CoupleUpdateVO.java, momentours/src/test/java/com/myhandjava/momentours/couple/command/application/service/CoupleCommandServiceImplTests.java, momentours/src/test/java/com/myhandjava/momentours/couple/query/service/CoupleQueryServiceImplTests.java
---
name: 커플 정보 수정 기능 개발
about: 커플 정보 수정(커플명, 커플사진, 사귄 날짜) 기능 개발 및 테스트 코드 추가
title: ''
assignees: ''
---
- 
- 
-
=> Couple update

momentours/src/main/java/com/myhandjava/momentours/config/AppConfig.java, momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/OpenAIService.java, momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/OpenAIServiceImpl.java, momentours/src/test/java/com/myhandjava/momentours/randomquestion/command/application/service/OpenAIServiceTests.java
---
name: 커플별 고유 랜덤질문 생성
about: openai api를 활용한 커플별 고유 랜덤질문 생성 기능 개발, 이 이후부터 환경변수에 제가 디코에 올린 걸 넣어주세요!
title: ''
assignees: ''
---
- 
- 
- 디스코드에 올린 환경변수 설정 및 gradle 주입 부탁드립니다.
=> Randomquestion create

momentours/src/main/java/com/myhandjava/momentours/todocourse/command/application/controller/TodoCourseController.java, momentours/src/main/java/com/myhandjava/momentours/todocourse/command/application/service/TodoCourseService.java, momentours/src/main/java/com/myhandjava/momentours/todocourse/command/application/service/TodoCourseServiceImpl.java, momentours/src/main/resources/application.yaml, momentours/src/test/java/com/myhandjava/momentours/todocourse/command/application/service/TodoCourseServiceImplTests.java
---
name: 예정 코스 삭제
about: 삭제하려는 해당 코스 삭제하는 기능 개발
title: #107 
assignees: ''
---
- 
- 
-
=> feat. 예정 코스 삭제

momentours/src/main/java/com/myhandjava/momentours/todocourse/command/application/controller/TodoCourseController.java, momentours/src/main/java/com/myhandjava/momentours/todocourse/command/application/dto/TodoCourseDTO.java, momentours/src/main/java/com/myhandjava/momentours/todocourse/command/application/service/TodoCourseService.java, momentours/src/main/java/com/myhandjava/momentours/todocourse/command/application/service/TodoCourseServiceImpl.java, momentours/src/test/java/com/myhandjava/momentours/todocourse/command/application/service/TodoCourseServiceImplTests.java
---
name: 예정 코스 좋아요 기능
about: 해당 예정 코스의 좋아요 추가 및 취소 기능 개발
title: #112 
assignees: ''
---
- 
- 
-
=> feat. 예정 코스 좋아요 기능

momentours/src/main/java/com/myhandjava/momentours/notification/command/application/controller/NotificationController.java, momentours/src/main/java/com/myhandjava/momentours/notification/command/application/dto/NotificationDTO.java, momentours/src/main/java/com/myhandjava/momentours/notification/command/application/service/NotificationService.java, momentours/src/main/java/com/myhandjava/momentours/notification/command/application/service/NotificationServiceImpl.java, momentours/src/main/java/com/myhandjava/momentours/notification/command/domain/aggregate/Notification.java, momentours/src/main/java/com/myhandjava/momentours/notification/command/domain/repository/NotificationRepository.java, momentours/src/main/java/com/myhandjava/momentours/notification/command/domain/vo/NotificationVO.java
---
name: #111 
about: 관리자는 공지를 작성할 수 있다.
title: 공지 작성
labels: feature
assignees: Haegwan-Choe
---
- 
- 
-
=> feat: 공지 작성

momentours/src/main/java/com/myhandjava/momentours/couple/command/application/controller/CoupleController.java, momentours/src/main/java/com/myhandjava/momentours/couple/query/controller/CoupleController.java, momentours/src/main/java/com/myhandjava/momentours/diary/command/application/controller/DiaryController.java, momentours/src/main/java/com/myhandjava/momentours/diary/query/controller/DiaryController.java, momentours/src/main/java/com/myhandjava/momentours/moment/command/application/controller/MomentController.java, momentours/src/main/java/com/myhandjava/momentours/moment/query/controller/MomentController.java, momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/controller/MomentCourseController.java, momentours/src/main/java/com/myhandjava/momentours/momentcourse/query/controller/MomentCourseController.java, momentours/src/main/java/com/myhandjava/momentours/notification/command/application/controller/NotificationController.java, momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/controller/ScheduleController.java, momentours/src/main/java/com/myhandjava/momentours/schedule/query/controller/ScheduleController.java, momentours/src/main/java/com/myhandjava/momentours/todocourse/command/application/controller/TodoCourseController.java, momentours/src/main/java/com/myhandjava/momentours/todocourse/query/controller/TodoCourseController.java
---
name: 프로젝트 코드 구조 수정
about: 프로젝트 잘못된거 수정
title: ' #117 '
labels: backend, feat
---
- 
- 
-
=> refactor: 프로젝트 코드 구조 수정

momentours/src/main/java/com/myhandjava/momentours/couple/command/application/controller/CoupleController.java, momentours/src/main/java/com/myhandjava/momentours/diary/command/application/controller/DiaryController.java, momentours/src/main/java/com/myhandjava/momentours/diary/query/controller/DiaryController.java, momentours/src/main/java/com/myhandjava/momentours/moment/command/application/controller/MomentController.java, momentours/src/main/java/com/myhandjava/momentours/moment/query/controller/MomentController.java, momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/controller/MomentCourseController.java, momentours/src/main/java/com/myhandjava/momentours/todocourse/command/application/controller/TodoCourseController.java, momentours/src/main/java/com/myhandjava/momentours/todocourse/query/controller/TodoCourseController.java
---
name: Claims 값 받기 수정
about: Claims으로 넘어온 토큰 값 꺼내는 코드 수정
title: ''
labels: backend, refactor
---
- 
- 
-
=> refactor: Claims 값 받기 수정

momentours/src/main/java/com/myhandjava/momentours/common/HttpStatusCode.java
Reverts myhandJAVA/be09-2nd-myHandJava-momentours#142
=> Revert "style: HttpStatusCode 포맷팅"

momentours/src/main/java/com/myhandjava/momentours/common/HttpStatusCode.java
Reverts myhandJAVA/be09-2nd-myHandJava-momentours#143
=> Revert "Revert "style: HttpStatusCode 포맷팅""

momentours/src/main/java/com/myhandjava/momentours/common/HttpStatusCode.java
---
name: HttpStatusCode 추가 작성
about: HttpStatusCode 추가 작성
title: ''
assignees: ''
---
- 
- 
-
=> style: HttpStatusCode 추가 작성

momentours/src/main/java/com/myhandjava/momentours/common/HttpStatusCode.java
---
name: Http 상태 코드 클래스 추가
about: 제 도메인 개발 pr 중 왠지 모르지만 빠져서 별도로 추가합니다.
title: ''
assignees: ''
---
- 상태 코드 클래스가 빠져있었습니다.
- 
-
=> refactor: HttpStatusCode 빼먹은 거 추가

momentours-gateway/.idea/modules/momentours-gateway.main.iml, momentours/src/main/java/com/myhandjava/momentours/diary/command/application/controller/DiaryController.java, momentours/src/main/java/com/myhandjava/momentours/diary/command/application/service/DiaryServiceImpl.java, momentours/src/main/java/com/myhandjava/momentours/diary/command/domain/repository/DiaryRepository.java, momentours/src/main/java/com/myhandjava/momentours/diary/query/controller/DiaryController.java, momentours/src/main/java/com/myhandjava/momentours/diary/query/repository/DiaryMapper.java, momentours/src/main/java/com/myhandjava/momentours/diary/query/service/DiaryService.java, momentours/src/main/java/com/myhandjava/momentours/diary/query/service/DiaryServiceImpl.java, momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/controller/MomentCourseController.java, momentours/src/main/java/com/myhandjava/momentours/momentcourse/query/controller/MomentCourseController.java, momentours/src/main/resources/mappers/diary/DiaryMapper.xml, momentours/src/test/java/com/myhandjava/momentours/diary/query/service/DiaryServiceImplTests.java
---
name: 프로젝트 코드 구조 수정 및 일기 1번만 쓰기 추가
about: 회원 코드 받아오는거 수정 및 일기 한번씩만 쓰기 추가
title: ' #117 '
labels: backend, refactor
---
- 
- 
-
=> refactor: 프로젝트 코드 구조 수정 및 일기 1번만 쓰기 추가

momentours/src/main/java/com/myhandjava/momentours/couple/command/application/service/CoupleServiceImpl.java, momentours/src/main/java/com/myhandjava/momentours/randomquestion/Exception/RandomQuestionException.java, momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/RandomQuestionAndReplyCommandService.java, momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/RandomQuestionAndReplyCommandServiceImpl.java, momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/domain/repository/RandomQuestionRepository.java, momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/domain/repository/RandomReplyRepository.java, momentours/src/main/resources/mappers/randomquestion/RandomQuestionMapper.xml, momentours/src/main/resources/mappers/randomquestion/RandomReplyMapper.xml
---
name: 커플 및 랜덤 질문 답변 수정
about: 커플이 삭제 시, 모든 랜덤질문과 답변 삭제, 답변 조회 시 삭제되지 않은 답변만 조회
title: ''
assignees: ''
---
- 
- 
-
=> Couple refactor

momentours-user/src/main/java/com/myhandjava/momentoursUser/command/applicaiton/service/UserServiceImpl.java, momentours-user/src/main/resources/application.yml, momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/controller/ScheduleController.java, momentours/src/main/java/com/myhandjava/momentours/schedule/command/domain/repository/ScheduleRepository.java, momentours/src/main/java/com/myhandjava/momentours/schedule/query/controller/ScheduleController.java, momentours/src/main/resources/application.yaml, momentours/src/test/java/com/myhandjava/momentours/schedule/command/application/service/ScheduleServiceImplTests.java, momentours/src/test/java/com/myhandjava/momentours/schedule/query/service/ScheduleServiceImplTests.java
스케줄 코드 1차 구조 개선
---
name: 스케줄 코드 구조 개선
about: 1) 테스트 코드 개선 2) HttpStatusCode 적용
title: #157
assignees: ''
---
- 
- 
-
=> Refactor: 스케줄 코드 부분 구조 개선

momentours/src/main/java/com/myhandjava/momentours/common/HttpStatusCode.java, momentours/src/main/java/com/myhandjava/momentours/diary/command/application/service/DiaryServiceImpl.java, momentours/src/main/java/com/myhandjava/momentours/diary/query/service/DiaryServiceImpl.java, momentours/src/main/java/com/myhandjava/momentours/file/command/application/service/FileServiceImpl.java, momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/service/MomentCourseServiceImpl.java
---
name: 파일, 일기, 추억코스 예외클래스 수정
about: 파일, 일기, 추억코스 예외클래스 수정과 CommonException 클래스 추가
title: ' #158 '
labels: backend, refactor
---
- 
- 
- HttpStatusCode클래스와 일기, 파일, 추억코스 impl 파일 보고 수정 부탁드립니당!
=> refactor: 예외클래스 수정

momentours/src/main/java/com/myhandjava/momentours/common/CommonException.java, momentours/src/main/java/com/myhandjava/momentours/common/HttpStatusCode.java, momentours/src/main/java/com/myhandjava/momentours/diary/command/application/service/DiaryServiceImpl.java, momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/RandomQuestionAndReplyCommandServiceImpl.java, momentours/src/main/java/com/myhandjava/momentours/randomquestion/query/service/RandomQuestionAndReplyQueryServiceImpl.java
---
name: 예외를 사용자 정의 예외를 던지도록 수정
about: Service에서 예외처리를 할 때 저희 프로젝트의 HttpStatusCode를 던지도록 수정했습니다.
title: ''
assignees: ''
---
- 
- 
-
=> refactor: 예외를 사용자 정의 예외를 던지도록 수정했습니다.

momentours/src/main/java/com/myhandjava/momentours/common/HttpStatusCode.java, momentours/src/main/java/com/myhandjava/momentours/couple/command/application/service/CoupleServiceImpl.java, momentours/src/main/java/com/myhandjava/momentours/couple/command/domain/repository/CoupleRepository.java, momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/RandomQuestionAndReplyCommandServiceImpl.java, momentours/src/main/java/com/myhandjava/momentours/randomquestion/query/service/RandomQuestionAndReplyQueryServiceImpl.java
---
name: 예외를 사용자 정의 예외를 던지도록 수정
about: 커플 조회 실패 시, NOT_FOUND_COUPLE 예외를 던지도록 수정했습니다.
title: ''
assignees: ''
---
- 
- 
-
=> refactor: 예외를 사용자 정의 예외를 던지도록 수정

momentours/src/main/java/com/myhandjava/momentours/diary/command/application/controller/DiaryController.java, momentours/src/main/java/com/myhandjava/momentours/diary/command/application/service/DiaryService.java, momentours/src/main/java/com/myhandjava/momentours/diary/command/application/service/DiaryServiceImpl.java, momentours/src/main/java/com/myhandjava/momentours/diary/command/domain/vo/RequestModifyDiaryVO.java, momentours/src/main/java/com/myhandjava/momentours/diary/command/domain/vo/RequestRegistDiaryVO.java, momentours/src/main/java/com/myhandjava/momentours/diary/query/service/DiaryServiceImpl.java, momentours/src/main/java/com/myhandjava/momentours/file/command/application/service/FileService.java, momentours/src/main/java/com/myhandjava/momentours/file/command/application/service/FileServiceImpl.java, momentours/src/main/java/com/myhandjava/momentours/file/query/service/FileService.java, momentours/src/main/java/com/myhandjava/momentours/file/query/service/FileServiceImpl.java, momentours/src/main/resources/mappers/diary/DiaryMapper.xml, momentours/src/test/java/com/myhandjava/momentours/diary/command/application/service/DiaryServiceImplTests.java
---
name: 일기 파일 관련 기능
about: 분명 만들었던 일기 파일 생성, 수정, 조회 기능 다시 되살림!
title: ' #166 '
labels: backend, refactor
---
- 
- 
-
=> refactor: 일기 파일 관련 기능

momentours/src/main/java/com/myhandjava/momentours/couple/command/application/controller/CoupleController.java, momentours/src/main/java/com/myhandjava/momentours/couple/command/application/dto/CoupleRegisterDTO.java, momentours/src/main/java/com/myhandjava/momentours/couple/command/domain/vo/CoupleRegistVO.java, momentours/src/main/java/com/myhandjava/momentours/couple/command/domain/vo/CoupleUpdateVO.java, momentours/src/main/java/com/myhandjava/momentours/couple/query/controller/CoupleController.java
---
name: Body에 커플 번호를 담도록 수정
about: 토큰에서 커플 번호를 추출하지 않고 requestBody에서 추출하도록 수정했습니다.
title: ''
assignees: ''
---
- 
- 
-
=> refactor: Body에 커플 번호를 담도록 수정

momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/controller/ScheduleController.java, momentours/src/main/java/com/myhandjava/momentours/schedule/query/controller/ScheduleController.java
---
name: Refactor: 스케줄 컨트롤러 리팩토링
about: 토큰 수정으로 인한 스케줄 컨트롤러 메소드 수정 
- RequestBody에서 회원번호 및 커플번호 받아옴
title: #171 
assignees: ''
---
- 
- 
-
=> Refactor: 스케줄 컨트롤러 리팩토링

momentours-user/src/main/java/com/myhandjava/momentoursUser/command/applicaiton/controller/UserController.java, momentours-user/src/main/java/com/myhandjava/momentoursUser/command/domain/vo/RequestCoupleVO.java, momentours/build.gradle, momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/controller/ScheduleController.java, momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/service/ScheduleService.java, momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/service/ScheduleServiceImpl.java, momentours/src/main/java/com/myhandjava/momentours/schedule/command/domain/vo/PutScheduleVO.java, momentours/src/main/java/com/myhandjava/momentours/schedule/command/domain/vo/UserCoupleNoVO.java, momentours/src/main/java/com/myhandjava/momentours/schedule/query/controller/ScheduleController.java, momentours/src/main/java/com/myhandjava/momentours/schedule/query/dto/FindScheduleDTO.java, momentours/src/main/java/com/myhandjava/momentours/schedule/query/repository/ScheduleMapper.java, momentours/src/main/java/com/myhandjava/momentours/schedule/query/service/ScheduleService.java, momentours/src/main/java/com/myhandjava/momentours/schedule/query/service/ScheduleServiceImpl.java, momentours/src/main/resources/mappers/schedule/ScheduleMapper.xml
정확한 유효성 검사를 실행하도록 스케줄 도메인 구조 변경
---
name: name : refactor: 스케줄 도메인 유효성 검사 리팩토링
about : CRUD 시 회원의 커플번호와 회원번호를 확인해 접근 권한 유효성을 체크하도록 구조 변경
title: #182
assignees: ''
---
- 
- 
- 유효성 검사 하는 부분 코드 참고하셔서 각자 도메인에서 만들면 될 것 같습니다!
=> refactor: 스케줄 유효성 검사 구조 리팩토링
